<a href="https://colab.research.google.com/github/matEOTCH24/Curso-Programacion-101---Maestria-UTEC/blob/main/Clase_3/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

In [ ]:
my_dict = {'47470368':'John Caballero',
           '45450912' : 'Piero Diaz',
           '42420522' : 'Julio Salgado'} #data hasheado o encriptado (datos sensibles), se pueden generar datos de forma aleatorio, asignando
my_dict

{'47470368': 'John Caballero'}

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona1 = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona1)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
# Acceder a un valor
print("Nombre:", persona1['nombre'])
print("Ciudad:", persona1.get('ciudad'))


Nombre: Ana
Ciudad: Lima


In [ ]:
persona1['genero'] = 'female' #asi se agrega un nuevo elemento al diccionario
print(persona1)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'genero': 'female'}


In [ ]:
del persona1['genero'] #asi se elimina del diciconario, solo necesita el key
print(persona1)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
list(persona1.keys()) #obtener las claves del diccionario

['nombre', 'edad', 'ciudad']

In [ ]:
list(persona1.values())

['Ana', 30, 'Lima']

In [ ]:
list(persona1)

['nombre', 'edad', 'ciudad']

In [ ]:
my_list = []
for item in persona1.items():
  my_list += list(item)

my_list

['nombre', 'Ana', 'edad', 30, 'ciudad', 'Lima']

In [ ]:
my_list = []
[[my_list.append(x),my_list.append(y)] for (x,y) in persona1.items()]

[[None, None], [None, None], [None, None]]

In [ ]:
# Obtener todas las claves
print(persona.keys())


In [ ]:
# Obtener todos los valores
print(persona.values())


In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [ ]:
auto = {'Marca':'Toyota', 'Modelo':'Corolla', 'Año':2022, 'Color' : 'Blanco'}
print(auto)

print("Marca: ", auto['Marca'])
print("Modelo: ", auto['Modelo'])
print("Año: ", auto['Año'])
print("Color: ", auto['Color'])

auto['Precio'] = 20_000
print(auto)

del auto['Color']
print(auto)

print('Keys:', list(auto.keys()))
print('Valores:', list(auto.values()))


{'Marca': 'Toyota', 'Modelo': 'Corolla', 'Año': 2022, 'Color': 'Blanco'}
Marca:  Toyota
Modelo:  Corolla
Año:  2022
Color:  Blanco
{'Marca': 'Toyota', 'Modelo': 'Corolla', 'Año': 2022, 'Color': 'Blanco', 'Precio': 20000}
{'Marca': 'Toyota', 'Modelo': 'Corolla', 'Año': 2022, 'Precio': 20000}
Keys: ['Marca', 'Modelo', 'Año', 'Precio']
Valores: ['Toyota', 'Corolla', 2022, 20000]


In [ ]:
grades = {'Eder':18
          'Roger':19
          }

In [4]:
alien_0 = {'x_position':0 , 'y_position': 25, 'speed':'medium'}
print("Original position: " + str(alien_0['x_position']))

if alien_0['speed'] == 'slow':
  x_increment = 1
elif alien_0['speed'] == 'medium':
  x_increment = 2
else:
  x_increment = 3

alien_0['x_position'] = alien_0['x_position'] + x_increment
print("New position X position: " + str(alien_0['x_position']))

Original position: 0
New position X position: 2


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [ ]:
#El set no permite trabajar con duplicados
my_list = ['var1', 'var2', 'var3', 'var4','var1','var2','var1']
set(my_list)

{'var1', 'var2', 'var3', 'var4'}

In [ ]:
my_set = {1,2,3,4,5}
print(my_set)

{1, 2, 3, 4, 5}


In [ ]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [ ]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [ ]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [ ]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


In [ ]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


In [ ]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [6]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



In [7]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
matriz_1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

matriz_2 = np.array([[10],
                     [20],
                     [30]])


In [9]:
matriz_1.shape # da el orden de m x n

(3, 3)

In [10]:
matriz_1 + matriz_2

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [11]:
matriz_1 * matriz_2

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [12]:
matriz_1.T #transpuesta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
np.trace(matriz_1) #la suma de la diagonal

15

In [19]:
np.random.randint(1,10,(3,3)) #primero es el rango, el otro es la orden m x n #esto es un tupla

array([[6, 3, 1],
       [1, 5, 8],
       [5, 3, 4]])

### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [30]:
ventas = {'Pantalones':[2,5,10,8,10,5,5] , 'Camisetas':[8,8,8,4,5,4,5] , 'Zapatos':[5,2,3,8,6,3,4]}
Ult_3_P = ventas['Pantalones'][-3:]
Ult_3_C = ventas['Camisetas'][-3:]
Ult_3_Z = ventas['Zapatos'][-3:]

print(f'Venta de los ultimos 3 dias de pantalones: {Ult_3_P} unidades')
print(f'Venta de los ultimos 3 dias de camisetas: {Ult_3_C} unidades')
print(f'Venta de los ultimos 3 dias de zapatos: {Ult_3_Z} unidades')


Total_Ventas_P = sum(ventas['Pantalones'])
Total_Ventas_C = sum(ventas['Camisetas'])
Total_Ventas_Z = sum(ventas['Zapatos'])
print(f'Total de ventas de pantalones = {Total_Ventas_P}')
print(f'Total de ventas de camisetas = {Total_Ventas_C}')
print(f'Total de ventas de zapatos = {Total_Ventas_Z}')

Promedio_P = round(Total_Ventas_P/len(ventas['Pantalones']),2)
Promedio_C = round(Total_Ventas_C/len(ventas['Camisetas']),2)
Promedio_Z = round(Total_Ventas_Z/len(ventas['Zapatos']),2)

print(f'Promedio de ventas diarias de pantalones = {Promedio_P}')
print(f'Promedio de ventas diarias de camisetas = {Promedio_C}')
print(f'Promedio de ventas diarias de zapatos = {Promedio_Z}')

clasif_pantalones = 'Buenas ventas' if Promedio_P > 5 else 'Malas Ventas'
clasif_camisetas = 'Buenas ventas' if Promedio_C > 5 else 'Malas Ventas'
clasif_zapatos = 'Buenas ventas' if Promedio_Z > 5 else 'Malas Ventas'

print(f'La clasificiacion de pantalones es {clasif_pantalones}')
print(f'La clasificiacion de camisetas es {clasif_camisetas}')
print(f'La clasificiacion de zapatos es {clasif_zapatos}')

Venta de los ultimos 3 dias de pantalones: [10, 5, 5] unidades
Venta de los ultimos 3 dias de camisetas: [5, 4, 5] unidades
Venta de los ultimos 3 dias de zapatos: [6, 3, 4] unidades
Total de ventas de pantalones = 45
Total de ventas de camisetas = 42
Total de ventas de zapatos = 31
Promedio de ventas diarias de pantalones = 6.43
Promedio de ventas diarias de camisetas = 6.0
Promedio de ventas diarias de zapatos = 4.43
La clasificiacion de pantalones es Buenas ventas
La clasificiacion de camisetas es Buenas ventas
La clasificiacion de zapatos es Malas Ventas


---

# Gracias por completar este laboratorio!

---